=== isuvajitsahoo/M3/XML/Demo/Emp.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="EmployeeDetails" maxOccurs="10">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EmployeeName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z][a-z]+"></xs:pattern>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="Age">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="18"></xs:minInclusive>
                    <xs:maxInclusive value="60"></xs:maxInclusive>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="Phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[7-9][0-9]{9}"></xs:pattern>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="City">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Pune"></xs:enumeration>
                    <xs:enumeration value="Mumbai"></xs:enumeration>
                    <xs:enumeration value="Bangalore"></xs:enumeration>
                    <xs:enumeration value="Hyderabad"></xs:enumeration>
                    <xs:enumeration value="Chennai"></xs:enumeration>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="DOJ" type="xs:date"></xs:element>
            </xs:sequence>
            <xs:attribute name="EmployeeID" type="xs:int" use="required"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== isuvajitsahoo/M3/XML/Demo/Employee.xml
<?xml version="1.0" encoding="utf-8"?>

<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Emp.xsd">
  <EmployeeDetails EmployeeID="12345">
    <EmployeeName>Ajay</EmployeeName>
    <Age>34</Age>
    <Phone>9087654321</Phone>
    <City>Mumbai</City>
    <DOJ>2015-02-02</DOJ>
  </EmployeeDetails>
  <EmployeeDetails EmployeeID="12346">
    <EmployeeName>Rahul</EmployeeName>
    <Age>24</Age>
    <Phone>9087564321</Phone>
    <City>Pune</City>
    <DOJ>2018-01-22</DOJ>
  </EmployeeDetails>
</Employees>
